### PR TITLE
fixed slapd.conf file, added dokken test suites and added to travis

### LINKED ISSUE #92: Broken slapd.con.erb
### Cookbook version
3.0.3

### Chef-client version
12.18.31 & 12.19.36

### Platform Details
Vagrant, AWS, Ubuntu 12.04, 16.04)

### Scenario:
A slapd that will start

### Steps to Reproduce:
node.force_override['openldap']['slapd_type'] = 'consumer' 
include_recipe 'openldap::default'

### Expected Result:
That slapd will start with resulting slapd.conf

### Actual Result:
slapd failes with following error: 

slapd[6336]: /etc/ldap/slapd.conf: line 86: Error: parse_syncrepl_line: unable to parse " 

It looks like a copypasta error in slapd.conf.erb: 
diff -c slapd.conf.erb /tmp/
*** slapd.conf.erb	2017-05-21 15:56:19.358637954 -0700
--- /tmp/slapd.conf.erb	2017-05-22 14:33:20.476953616 -0700
***************
*** 104,110 ****
    scope=sub
    schemachecking=off
    bindmethod=simple
!   binddn="<%= node['openldap']['syncrepl_cn'] %>,<%= node['openldap']['basedn'] %>" read"
    starttls=<%= node['openldap']['syncrepl_use_tls'] %>
    credentials="<%= node['openldap']['slapd_replpw'] %>"
  <% end -%>
--- 104,110 ----
    scope=sub
    schemachecking=off
    bindmethod=simple
!   binddn="<%= node['openldap']['syncrepl_cn'] %>,<%= node['openldap']['basedn'] %>"
    starttls=<%= node['openldap']['syncrepl_use_tls'] %>
    credentials="<%= node['openldap']['slapd_replpw'] %>"
  <% end -%>
***************
*** 153,158 ****
  access to *
          by group.exact="cn=administrators,<%= node['openldap']['basedn'] %>" write
  <% if node['openldap']['slapd_type'] == "provider" -%>
!         by by dn="<%= node['openldap']['syncrepl_cn'] %>,<%= node['openldap']['basedn'] %>" read
  <% end -%>
          by * read
--- 153,158 ----
  access to *
          by group.exact="cn=administrators,<%= node['openldap']['basedn'] %>" write
  <% if node['openldap']['slapd_type'] == "provider" -%>
!         by dn="<%= node['openldap']['syncrepl_cn'] %>,<%= node['openldap']['basedn'] %>" read
  <% end -%>
          by * read

### PR DESCRIPTION
**Pull request by finchr**
### Description

Fixes slapd.conf when slapd_type is set. I also implement dokken tests and added two to travis so the conditions get tested for every pull request.

### Issues Resolved

#92, #94, #95 

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

File: metadata.rb [hunk 1]
```diff
@@ -4,7 +4,7 @@
 license           'Apache-2.0'
 description       'Installs and configures OpenLDAP (slapd) an open source implementation of LDAP.'
 long_description  IO.read(File.join(File.dirname(__FILE__), 'README.md'))
-version           '3.1.1'
+version           '3.1.2'
```
Comment (iennae) [inline metadata.rb]: please don't update version information in metadata. we'll do this when we do the release. thanks.

Comment (finchr) [inline metadata.rb]: oh, ok. I'll back it out ....
